services:
  - type: web
    name: metabase
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /api/health
    envVars:
      - key: MB_DB_TYPE
        value: postgres
      - key: MB_DB_DBNAME
        value: metabase
      - key: MB_DB_PORT
        value: "5432"
      - key: MB_DB_USER
        fromDatabase:
          name: metabase-db
          property: user
      - key: MB_DB_PASS
        fromDatabase:
          name: metabase-db
          property: password
      - key: MB_DB_HOST
        fromDatabase:
          name: metabase-db
          property: host

databases:
  - name: metabase-db
    plan: standard